import dayjs from 'dayjs/esm';

import { IRegVenta, NewRegVenta } from './reg-venta.model';

export const sampleWithRequiredData: IRegVenta = {
  id: '3431caf2-afc1-42b2-bf3b-343caa50548e',
  periodo: 'synthesizing Gourde',
  cuo: 'Estratega Municipio',
  fecEmiComp: dayjs('2024-06-13T09:56'),
  tipComp: 'copy Buckinghamshire heurística',
  nroSerieComp: 'Gorro Madera',
  nroComp: 'virtual deliverables Ensalada',
  tipDocCli: 'Asociado Colegio por',
  nroDocCli: 'implementación el',
  apeRazSocCli: 'parse Granito a',
  baseImpOperGrav: 34503,
  dsctoBaseImp: 4110,
  igvIpm: 14085,
  dsctoIgvIpm: 24092,
  impOpeExo: 41657,
  impTotOpeInafec: 93242,
  importeTotalComp: 92348,
  codMoneda: 'estandardización mediante FTP',
  tipCambio: 63091,
  indDel: true,
  fecCrea: dayjs('2024-06-12T22:31'),
  usuCrea: 'Diseñador Violeta auxiliary',
  ipCrea: 'Inteligente Auto',
};

export const sampleWithPartialData: IRegVenta = {
  id: '309448f1-e5f0-48ef-8b9e-a504db39656b',
  periodo: 'navigating Albania',
  cuo: 'driver Funcionario Hormigon',
  fecEmiComp: dayjs('2024-06-13T15:43'),
  fecVencComp: dayjs('2024-06-13T10:03'),
  tipComp: 'Georgia Música',
  nroSerieComp: 'redundant',
  nroComp: 'Poland',
  consoDia: 'capacitor transmitting',
  tipDocCli: 'indexing ROI',
  nroDocCli: 'interface',
  apeRazSocCli: 'Optimización',
  baseImpOperGrav: 70310,
  dsctoBaseImp: 5717,
  igvIpm: 37601,
  dsctoIgvIpm: 93436,
  impOpeExo: 31085,
  impTotOpeInafec: 68781,
  impSecCons: 672,
  impVentArroz: 87664,
  importeTotalComp: 54092,
  codMoneda: 'quantifying payment',
  tipCambio: 73736,
  fecEmiModif: dayjs('2024-06-13T11:56'),
  tipCompModif: 'Galicia payment Buckinghamshire',
  nroCompModif: 'niches Investigación',
  estadoOperaCancMp: 'Borders',
  campoLibre: 'Canarias local',
  formPago: 'Apartamento Account navigating',
  indDel: true,
  fecCrea: dayjs('2024-06-13T10:47'),
  usuCrea: 'generación Bicicleta',
  ipCrea: 'Proactivo Especialista Negro',
  fecModif: dayjs('2024-06-12T19:44'),
};

export const sampleWithFullData: IRegVenta = {
  id: '2f713e08-ec97-4c96-8f99-cef655165e6d',
  periodo: 'sensible indexing',
  cuo: 'withdrawal Ouguiya',
  asientContab: 'invoice Dinánmico',
  fecEmiComp: dayjs('2024-06-13T00:32'),
  fecVencComp: dayjs('2024-06-12T22:16'),
  tipComp: 'Refinado',
  nroSerieComp: 'payment',
  nroComp: 'potenciada 1080p',
  consoDia: 'parsing',
  tipDocCli: 'driver visualize Moda',
  nroDocCli: 'synthesizing Directo',
  apeRazSocCli: 'Facilitador',
  valFacExpor: 68867,
  baseImpOperGrav: 8041,
  dsctoBaseImp: 3788,
  igvIpm: 69455,
  dsctoIgvIpm: 31088,
  impOpeExo: 15235,
  impTotOpeInafec: 76485,
  impSecCons: 88054,
  baseImpArroz: 7411,
  impVentArroz: 8214,
  otrosNoBaseImp: 25718,
  importeTotalComp: 18073,
  codMoneda: 'Azul',
  tipCambio: 80993,
  fecEmiModif: dayjs('2024-06-13T12:46'),
  tipCompModif: 'application syndicate Calle',
  nroSerieCompModif: 'Hong',
  nroCompModif: 'wireless',
  identContrato: 'exploit Madera',
  errTipUno: 'compressing',
  indCompVancMp: 'Colegio generate',
  estadoOperaCancMp: 'Puerta Prolongación back',
  campoLibre: 'navigating',
  formPago: 'Futuro',
  moneda: 'open-source Director',
  indDel: false,
  fecCrea: dayjs('2024-06-13T05:20'),
  usuCrea: 'Morado',
  ipCrea: 'Auto 5th',
  fecModif: dayjs('2024-06-13T05:42'),
  usuModif: 'Bedfordshire Aldea Datos',
  ipModif: 'driver Madera Colegio',
};

export const sampleWithNewData: NewRegVenta = {
  periodo: 'mesh',
  cuo: 'Hong cross-media',
  fecEmiComp: dayjs('2024-06-12T19:13'),
  tipComp: 'de monetize global',
  nroSerieComp: 'Automatizado Programable 1080p',
  nroComp: 'enable',
  tipDocCli: 'Chad Eslovaquia Re-contextualizado',
  nroDocCli: 'Galicia',
  apeRazSocCli: 'Asimilado hack',
  baseImpOperGrav: 23168,
  dsctoBaseImp: 89905,
  igvIpm: 25864,
  dsctoIgvIpm: 77890,
  impOpeExo: 99755,
  impTotOpeInafec: 43468,
  importeTotalComp: 74040,
  codMoneda: 'iterate',
  tipCambio: 83994,
  indDel: false,
  fecCrea: dayjs('2024-06-13T10:48'),
  usuCrea: 'bypassing plug-and-play Adelante',
  ipCrea: 'methodologies cross-platform',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
