export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  CAJERO = 'ROLE_CAJERO',
  MESERO = 'ROLE_MESERO',
  COCINERO = 'ROLE_COCINERO',
  GERENTE = 'ROLE_GERENTE',
  INVENTARIO = 'ROLE_INVENTARIO'
}
