import dayjs from 'dayjs/esm';

import { IRegCompras, NewRegCompras } from './reg-compras.model';

export const sampleWithRequiredData: IRegCompras = {
  id: '50a2b668-facb-476c-b651-249b10fb87e2',
  periodo: 'override',
  cuo: 'system invoice circuit',
  fecEmiComp: dayjs('2024-06-12T23:38'),
  tipComp: 'fallos',
  nroSerieComp: 'Rial',
  nroComp: 'AGP Configurable invoice',
  tipDocProv: 'Práctico',
  nroDocProv: 'Respuesta',
  nomApeRazSocProv: 'Realineado Oficial index',
  baseImponible: 21137,
  montoIgv: 55092,
  baseImponible2: 96057,
  montoIgv2: 56810,
  montoIgv3: 3610,
  indDel: false,
  fecCrea: dayjs('2024-06-12T18:29'),
  usuCrea: 'digital online Zambian',
  ipCrea: 'Guapo Diseñador',
};

export const sampleWithPartialData: IRegCompras = {
  id: '1746221f-ad31-4598-a04d-89471b939497',
  periodo: 'Investment Sabroso',
  cuo: 'ADP',
  fecEmiComp: dayjs('2024-06-13T11:02'),
  tipComp: 'Vietnam',
  nroSerieComp: 'Arroyo Patatas Berkshire',
  anhoEmisionDua: 'Verde firmware array',
  nroComp: 'networks bandwidth',
  tipDocProv: 'overriding',
  nroDocProv: 'Malawi quantify',
  nomApeRazSocProv: 'por Planificador',
  baseImponible: 81480,
  montoIgv: 2242,
  baseImponible2: 29556,
  montoIgv2: 78111,
  montoIgv3: 67852,
  montoIsc: 71093,
  importeTotal: 13498,
  codMoneda: 'Valenciana connecting',
  tipCompModif: 'Kiribati',
  nroSerieCompModif: 'Francia Vasco quantify',
  nroCompModif: 'Valenciana Juguetería',
  fecEmiDetracc: dayjs('2024-06-13T16:10'),
  identContrato: 'infrastructures',
  errTipDos: 'Consultor solución',
  indCompPagoMedPago: 'SMS Colegio Kenia',
  estado: 68915,
  indDel: true,
  fecCrea: dayjs('2024-06-13T10:05'),
  usuCrea: 'Pizza',
  ipCrea: 'Programa',
};

export const sampleWithFullData: IRegCompras = {
  id: '01f7dac4-093b-428c-8be0-080014994408',
  periodo: 'navigate Navidad',
  cuo: 'Won',
  asientContab: 'Adelante Diseñador Práctico',
  fecEmiComp: dayjs('2024-06-13T05:21'),
  fecVencComp: dayjs('2024-06-12T18:24'),
  tipComp: 'firewall Humano',
  nroSerieComp: 'Bicicleta',
  anhoEmisionDua: 'heurística Cambridgeshire',
  nroComp: 'Sorprendente harness',
  nroFinal: 'AGP networks deliver',
  tipDocProv: 'Senda Gerente invoice',
  nroDocProv: 'RAM',
  nomApeRazSocProv: 'contingencia',
  baseImponible: 82297,
  montoIgv: 33124,
  baseImponible2: 87264,
  montoIgv2: 18144,
  baseImponible3: 43437,
  montoIgv3: 55076,
  montoNoGravado: 80499,
  montoIsc: 2345,
  impConsBols: 64156,
  otrosCargos: 60572,
  importeTotal: 55568,
  codMoneda: 'Optimizado',
  tipCambio: 55225,
  fecEmiModif: dayjs('2024-06-13T11:22'),
  tipCompModif: 'parse scale',
  nroSerieCompModif: 'Operaciones',
  codDuaRef: 'multi-byte Soluciones Baleares',
  nroCompModif: 'services granular previsión',
  fecEmiDetracc: dayjs('2024-06-13T07:58'),
  nroConstDetracc: 'Sector calculating Toallas',
  indCompSujRetenc: 'moderador reboot',
  clasBienesyServicios: 'Rampa Rústico AGP',
  identContrato: 'Electrónica visionary',
  errTipUno: 'Islandia',
  errTipDos: 'Senior panel',
  errTipTres: 'Inteligente',
  errTipCuatro: 'extensible',
  indCompPagoMedPago: 'channels deposit Vía',
  estado: 41244,
  campoLibre: 'Proactivo Toallas',
  indDel: false,
  fecCrea: dayjs('2024-06-13T16:11'),
  usuCrea: 'Pelota capacidad',
  ipCrea: 'SAS concepto Comunidad',
  fecModif: dayjs('2024-06-12T20:32'),
  usuModif: 'Lebanese',
  ipModif: 'Negro invoice Rústico',
};

export const sampleWithNewData: NewRegCompras = {
  periodo: 'Account',
  cuo: 'Money invoice',
  fecEmiComp: dayjs('2024-06-13T00:08'),
  tipComp: 'generación Auto República',
  nroSerieComp: 'protocol morph',
  nroComp: 'Coordinador mindshare',
  tipDocProv: 'Humano',
  nroDocProv: 'payment',
  nomApeRazSocProv: 'transmit',
  baseImponible: 66656,
  montoIgv: 97987,
  baseImponible2: 66596,
  montoIgv2: 61376,
  montoIgv3: 90676,
  indDel: false,
  fecCrea: dayjs('2024-06-12T23:17'),
  usuCrea: 'calculating',
  ipCrea: 'Extrarradio Avenida Descentralizado',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
